# Generated by Django 2.1 on 2019-01-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('matchdate', models.DateField(primary_key=True, serialize=False)),
                ('matchtype', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDaySquadBlue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.MatchDay')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDaySquadRed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.MatchDay')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('ST', 'Striker')], default='DF', max_length=2)),
                ('preferred_foot', models.CharField(choices=[('RT', 'Right'), ('LT', 'Left'), ('BT', 'Both')], default='RT', max_length=5)),
                ('trait', models.TextField(default='', max_length=50)),
                ('totalwins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redsscore', models.IntegerField()),
                ('bluescore', models.IntegerField()),
                ('matchdate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.MatchDay')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('home_deleteme', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='results',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Team'),
        ),
        migrations.AddField(
            model_name='matchdaysquadred',
            name='playername',
            field=models.ManyToManyField(to='manager.Player'),
        ),
        migrations.AddField(
            model_name='matchdaysquadred',
            name='teamname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Team'),
        ),
        migrations.AddField(
            model_name='matchdaysquadblue',
            name='playername',
            field=models.ManyToManyField(to='manager.Player'),
        ),
        migrations.AddField(
            model_name='matchdaysquadblue',
            name='teamname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Team'),
        ),
    ]
