# Generated by Django 2.1 on 2019-01-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_player_totalpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='home_deleteme',
        ),
    ]
