# Generated by Django 2.1 on 2019-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190102_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='matchtype',
            field=models.CharField(choices=[('5', '5-a-side'), ('8', '8-a-side')], default='5', max_length=10),
        ),
    ]
