# Generated by Django 2.1 on 2019-01-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190113_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='totalpoints',
            field=models.IntegerField(default=0),
        ),
    ]
