# Generated by Django 2.1.2 on 2019-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_team_home_deleteme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdaysquadblue',
            name='matchdate',
        ),
        migrations.RemoveField(
            model_name='matchdaysquadblue',
            name='playername',
        ),
        migrations.RemoveField(
            model_name='matchdaysquadblue',
            name='teamname',
        ),
        migrations.RemoveField(
            model_name='matchdaysquadred',
            name='matchdate',
        ),
        migrations.RemoveField(
            model_name='matchdaysquadred',
            name='playername',
        ),
        migrations.RemoveField(
            model_name='matchdaysquadred',
            name='teamname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='preferred_foot',
        ),
        migrations.RemoveField(
            model_name='player',
            name='totaldraws',
        ),
        migrations.RemoveField(
            model_name='player',
            name='totallosses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='totalpoints',
        ),
        migrations.RemoveField(
            model_name='player',
            name='totalwins',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trait',
        ),
        migrations.RemoveField(
            model_name='results',
            name='winner',
        ),
        migrations.AlterField(
            model_name='matchday',
            name='matchtype',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='MatchDaySquadBlue',
        ),
        migrations.DeleteModel(
            name='MatchDaySquadRed',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
