# Generated by Django 2.1.5 on 2019-01-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190126_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.ManyToManyField(through='manager.PlayerPoints', to='manager.MatchDay'),
        ),
    ]
