# Generated by Django 2.1.5 on 2019-02-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_player_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField(blank=True, null=True)),
                ('date', models.DateField()),
                ('goals', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='playerpoints',
            name='matchdate',
        ),
        migrations.RemoveField(
            model_name='playerpoints',
            name='name',
        ),
        migrations.RemoveField(
            model_name='results',
            name='matchdate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='MatchDay',
        ),
        migrations.DeleteModel(
            name='PlayerPoints',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.AddField(
            model_name='team',
            name='player',
            field=models.ManyToManyField(through='manager.Match', to='manager.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Team'),
        ),
    ]
