# Generated by Django 2.1.2 on 2019-02-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_player_preferredfoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='Defender', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='trait',
            field=models.CharField(default='Pays on time', max_length=50),
        ),
    ]
