# Generated by Django 2.1.2 on 2019-02-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190204_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goalsscored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='motmawards',
            field=models.IntegerField(default=0),
        ),
    ]
